### PR TITLE
Updated to work with current (leaflet-based) dynmap 0.20

### PR DESCRIPTION
**Pull request by mokus0**

### CODE REVIEW

**Comment by mokus0** [comment]
I'm not sure what the normal way would be to submit 2 independent pull requests (I probably should have created them in separate branches and then merged) but I also have an unrelated change to settings.js in my fork, which makes it insert the settings panel above the players panel.  This is because the current dynmap resizes the player list whenever it changes and the height calculation it uses assumes it is the last panel.  It looked like a whole lot less work to work around it in landmarks than to fix it in dynmap, so that's what I did.  Feel free to pull that as well, or if you prefer I could try to rebase it into a separate branch and make a formal pull request.

**Comment by dfyx** [comment]
I'm away from home for a few days. I'll have look as soon as I'm home.

**Comment by dfyx** [comment]
Sorry for abandoning this. To be honest I probably just forgot it when I came home from my vacation.

**Comment by mokus0** [comment]
No problem, I often lose track of PRs due to real-life distractions too.  I had completely forgotten about this one too, was just cleaning house on my Github account.

**Pull request closed without merging**
